### Q_1: create 2D-array that contain even numbers between 0-18...??

In [7]:
import numpy as np

In [9]:
toto = []
for i in range(0,19):
    if i%2 == 0:
        toto.append(i)
toto = np.array(toto).reshape(2,-1)
toto

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [8]:
hehe = np.array([ v for v in range(0,19) if v%2==0])
hehe = hehe.reshape(2,-1)
hehe

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [10]:
loool = np.arange(0,19,2) 
loool = loool.reshape(2,-1)
loool

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

### Q_2: Replace the negative values with 0 in random array that have values in range (-6,6)

In [45]:
koko = np.random.randint(-6,6,size=10)
print(f"before: {koko}")
koko[koko<0]=0
print(f"after: {koko}")

before: [ 0 -4  5 -6  0 -1 -1  0 -1  2]
after: [0 0 5 0 0 0 0 0 0 2]


#### OR

In [46]:
dodo = np.random.randint(-6,6,size=10)
print(f"before: {dodo}")

for i in range(10) :
    if dodo[i] < 0 :
        dodo[i]=0
print(f"after: {dodo}")

before: [ 2  3  2 -5 -1  4 -2 -1  2 -3]
after: [2 3 2 0 0 4 0 0 2 0]


### Q_3 :  How to compute ((A+B)*(-A/2)) ?  where A,B are random arrays with dimension (3,3) 

In [36]:
A = np.random.random(size=(3,3))
B = np.random.random(size=(3,3))

In [39]:
((A+B)*(-A/2))

array([[-0.62494108, -0.37177161, -0.41468995],
       [-0.20948529, -0.01135809, -0.04631284],
       [-0.12785761, -0.04072251, -0.0170935 ]])

In [40]:
# وفي طريقة بدائية اوي لو عايزين نصدع نفسنا  
(np.add(A,B))*(np.divide(-A,2))

array([[-0.62494108, -0.37177161, -0.41468995],
       [-0.20948529, -0.01135809, -0.04631284],
       [-0.12785761, -0.04072251, -0.0170935 ]])

### Q_4: How to concatenate two arrays horizontally..?

In [49]:
D = np.concatenate((koko,dodo),axis=0)
D

array([0, 0, 5, 0, 0, 0, 0, 0, 0, 2, 2, 3, 2, 0, 0, 4, 0, 0, 2, 0])

#### Q_5: Create a random vector of size 3x3 and sort values in Its columns

In [51]:
# vector and multidimensional?🤨
m= np.random.randint(1,100,size=(3,3))
m

array([[18, 61, 27],
       [90, 62, 35],
       [57, 40, 42]])

In [53]:
np.sort(m,axis=0)

array([[18, 40, 27],
       [57, 61, 35],
       [90, 62, 42]])